import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";

// Helper to format dates
const getFormattedDate = () => {
  const d = new Date();
  return d.toISOString().split("T")[0];
};

/**
 * Common PDF styling setup
 */
const setupPDFDoc = (title: string, subtitle: string, metaFields: { label: string; value: string }[]) => {
  const doc = new jsPDF("p", "pt", "a4");
  
  // Page boundaries (A4 size in points: 595 x 842)
  const margin = 20;
  
  // Logo Text
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.setTextColor(124, 58, 237); // #7c3aed (purple)
  doc.text("SYNTRIX AI", margin, 35);

  // Subheader title
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.setTextColor(17, 17, 17); // #111111
  doc.text(title, margin, 55);

  // Subtitle/Context
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(100, 116, 139); // Slate-500
  doc.text(subtitle, margin, 70);

  // Meta info grid
  let currentY = 85;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  doc.setTextColor(71, 85, 105); // Slate-600

  metaFields.forEach((meta) => {
    doc.text(`${meta.label}:`, margin, currentY);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(17, 17, 17);
    doc.text(meta.value, margin + 80, currentY);
    currentY += 14;
    doc.setFont("helvetica", "bold");
    doc.setTextColor(71, 85, 105);
  });

  // Draw separator line
  doc.setDrawColor(226, 232, 240); // Slate-200
  doc.setLineWidth(1);
  doc.line(margin, currentY + 5, 575, currentY + 5);

  return { doc, startY: currentY + 25 };
};

/**
 * Add a standard section header to a PDF page
 */
const addSectionHeader = (doc: jsPDF, title: string, y: number): number => {
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(124, 58, 237); // #7c3aed purple
  doc.text(title.toUpperCase(), 20, y);
  doc.setDrawColor(124, 58, 237);
  doc.setLineWidth(0.5);
  doc.line(20, y + 4, 120, y + 4);
  return y + 16;
};

/**
 * Draw footer on the current page
 */
const drawFooter = (doc: jsPDF, footerText: string = "Generated by Syntrix AI • syntrixai.com") => {
  const totalPages = (doc as any).internal.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(148, 163, 184); // Slate-400
    doc.text(footerText, 20, 825);
    doc.text(`Page ${i} of ${totalPages}`, 520, 825);
  }
};

/**
 * 1. ATS Report PDF Export
 */
export const generateATSReportPDF = (atsData: any, candidateName: string = "Executive Candidate") => {
  const { doc, startY } = setupPDFDoc(
    "ATS Analysis Report",
    "Candidate Resume Compatibility & Score Assessment",
    [
      { label: "Candidate", value: candidateName },
      { label: "Date Generated", value: new Date().toLocaleDateString() },
      { label: "Core Service", value: "Syntrix ATS Scanner Engine" }
    ]
  );

  let y = startY;

  // Section 1: Score Summary Table
  y = addSectionHeader(doc, "1. Score Summary", y);
  
  const scoreRows = [
    ["Overall ATS Score", `${atsData.scores?.overall || 0} / 100`],
    ["Technical Depth", `${atsData.scores?.technical_depth || 0} / 100`],
    ["ATS Optimization", `${atsData.scores?.ats_optimization || 0} / 100`],
    ["Recruiter Readability", `${atsData.scores?.recruiter_readability || 0} / 100`],
    ["Project Quality", `${atsData.scores?.project_quality || 0} / 100`]
  ];

  autoTable(doc, {
    startY: y,
    head: [["Performance Metric", "Score Grade"]],
    body: scoreRows,
    theme: "striped",
    headStyles: { fillColor: [124, 58, 237], textColor: [255, 255, 255], fontStyle: "bold" },
    bodyStyles: { textColor: [17, 17, 17], fontSize: 9 },
    alternateRowStyles: { fillColor: [249, 249, 249] },
    margin: { left: 20, right: 20 },
    didDrawPage: (data) => {
      y = data.cursor ? data.cursor.y + 25 : y + 100;
    }
  });

  // Section 2: Critical Keyword Gaps
  if (atsData.missing_keywords && atsData.missing_keywords.length > 0) {
    if (y > 750) { doc.addPage(); y = 40; }
    y = addSectionHeader(doc, "2. Critical Keyword Gaps", y);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(17, 17, 17);
    
    atsData.missing_keywords.forEach((keyword: string) => {
      doc.text(`• ${keyword}`, 30, y);
      y += 14;
    });
    y += 10;
  }

  // Section 3: Parsing & Formatting Issues
  if (atsData.formatting_issues && atsData.formatting_issues.length > 0) {
    if (y > 750) { doc.addPage(); y = 40; }
    y = addSectionHeader(doc, "3. Parsing & Formatting Issues", y);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(17, 17, 17);

    atsData.formatting_issues.forEach((issue: string) => {
      doc.text(`• ${issue}`, 30, y);
      y += 14;
    });
    y += 10;
  }

  // Section 4: Weak Bullets & Improvements
  if (atsData.weak_bullets && atsData.weak_bullets.length > 0) {
    if (y > 700) { doc.addPage(); y = 40; }
    y = addSectionHeader(doc, "4. Weak Bullets & Improvements", y);

    atsData.weak_bullets.forEach((bullet: string, idx: number) => {
      if (y > 720) { doc.addPage(); y = 40; }
      doc.setFont("helvetica", "bold");
      doc.setFontSize(9);
      doc.setTextColor(225, 29, 72); // rose-600 original red
      doc.text(`Original Bullet ${idx + 1}:`, 30, y);
      y += 12;

      doc.setFont("helvetica", "normal");
      doc.setTextColor(17, 17, 17);
      const originalLines = doc.splitTextToSize(bullet, 520);
      doc.text(originalLines, 35, y);
      y += originalLines.length * 12 + 2;

      doc.setFont("helvetica", "bold");
      doc.setTextColor(16, 185, 129); // emerald-500 optimized green
      doc.text("Improved (STAR Format):", 30, y);
      y += 12;

      doc.setFont("helvetica", "italic");
      doc.setTextColor(17, 17, 17);
      // Fallback recommendation
      const recommendation = (atsData.improvement_suggestions && atsData.improvement_suggestions[idx]) || 
        "Spearheaded implementation refactoring that resulted in a measurable 30% performance speedup.";
      const improvedLines = doc.splitTextToSize(recommendation, 520);
      doc.text(improvedLines, 35, y);
      y += improvedLines.length * 12 + 15;
    });
  }

  drawFooter(doc);
  doc.save(`syntrix-ats-report-${getFormattedDate()}.pdf`);
};

/**
 * 2. JD Match Report PDF Export
 */
export const generateJDReportPDF = (jdData: any, candidateName: string = "Executive Candidate", targetRole: string = "Target Role") => {
  const { doc, startY } = setupPDFDoc(
    "JD Match Report",
    "Candidate Resume Overlay & Position Alignment Analysis",
    [
      { label: "Candidate", value: candidateName },
      { label: "Target Role", value: targetRole },
      { label: "Date Generated", value: new Date().toLocaleDateString() },
      { label: "Core Service", value: "Syntrix Real-Time JD Matcher" }
    ]
  );

  let y = startY;

  // Section 1: Match Summary Table
  y = addSectionHeader(doc, "1. Match Summary", y);
  
  const summaryRows = [
    ["Role Alignment Percentage", `${jdData.match_percentage || 0}%`],
    ["AI Confidence Rating", `${jdData.confidence_score || 0}%`]
  ];

  autoTable(doc, {
    startY: y,
    head: [["Metric", "Value Overlay"]],
    body: summaryRows,
    theme: "striped",
    headStyles: { fillColor: [124, 58, 237], textColor: [255, 255, 255], fontStyle: "bold" },
    bodyStyles: { textColor: [17, 17, 17], fontSize: 9 },
    alternateRowStyles: { fillColor: [249, 249, 249] },
    margin: { left: 20, right: 20 },
    didDrawPage: (data) => {
      y = data.cursor ? data.cursor.y + 25 : y + 80;
    }
  });

  // Section 2: Matched Skills (Green)
  if (jdData.matched_skills && jdData.matched_skills.length > 0) {
    if (y > 750) { doc.addPage(); y = 40; }
    y = addSectionHeader(doc, "2. Matched Skills", y);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(16, 185, 129); // emerald-500 green

    const matchedList = jdData.matched_skills.join(" • ");
    const matchedLines = doc.splitTextToSize(matchedList, 520);
    doc.text(matchedLines, 30, y);
    y += matchedLines.length * 12 + 15;
  }

  // Section 3: Skill Gaps (Red)
  if (jdData.missing_skills && jdData.missing_skills.length > 0) {
    if (y > 750) { doc.addPage(); y = 40; }
    y = addSectionHeader(doc, "3. Critical Skill Gaps", y);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(225, 29, 72); // rose-600 red

    const missingList = jdData.missing_skills.join(" • ");
    const missingLines = doc.splitTextToSize(missingList, 520);
    doc.text(missingLines, 30, y);
    y += missingLines.length * 12 + 15;
  }

  // Section 4: Transferable Strengths
  if (jdData.transferable_skills && jdData.transferable_skills.length > 0) {
    if (y > 750) { doc.addPage(); y = 40; }
    y = addSectionHeader(doc, "4. Transferable Strengths", y);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(17, 17, 17);

    jdData.transferable_skills.forEach((strength: string) => {
      doc.text(`• ${strength}`, 30, y);
      y += 14;
    });
    y += 10;
  }

  // Section 5: Experience Alignment
  if (jdData.experience_alignment) {
    if (y > 740) { doc.addPage(); y = 40; }
    y = addSectionHeader(doc, "5. Experience Alignment", y);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(17, 17, 17);

    const alignLines = doc.splitTextToSize(jdData.experience_alignment, 520);
    doc.text(alignLines, 30, y);
    y += alignLines.length * 12 + 15;
  }

  // Section 6: Recommended Improvements
  if (jdData.recommended_improvements && jdData.recommended_improvements.length > 0) {
    if (y > 750) { doc.addPage(); y = 40; }
    y = addSectionHeader(doc, "6. Recommended Improvements", y);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(17, 17, 17);

    jdData.recommended_improvements.forEach((rec: string, idx: number) => {
      const recLines = doc.splitTextToSize(`${idx + 1}. ${rec}`, 520);
      doc.text(recLines, 30, y);
      y += recLines.length * 12 + 2;
    });
    y += 10;
  }

  // Section 7: Likely Interview Topics
  if (jdData.likely_interview_topics && jdData.likely_interview_topics.length > 0) {
    if (y > 750) { doc.addPage(); y = 40; }
    y = addSectionHeader(doc, "7. Likely Interview Topics", y);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(17, 17, 17);

    jdData.likely_interview_topics.forEach((topic: string, idx: number) => {
      const topicLines = doc.splitTextToSize(`${idx + 1}. ${topic}`, 520);
      doc.text(topicLines, 30, y);
      y += topicLines.length * 12 + 2;
    });
  }

  drawFooter(doc);
  doc.save(`syntrix-jd-report-${getFormattedDate()}.pdf`);
};

/**
 * 3. Interview Report PDF Export
 */
export const generateInterviewReportPDF = (sessionData: {
  sessionId: string;
  role: string;
  type: string;
  questions: any[];
  answers: Record<number, string>;
  evaluations: Record<number, any>;
}, candidateName: string = "Executive Candidate") => {
  const { doc, startY } = setupPDFDoc(
    "Mock Interview Report",
    `Simulation Q&A Assessment - ${sessionData.type || "Technical"} Track`,
    [
      { label: "Candidate", value: candidateName },
      { label: "Role Context", value: sessionData.role || "Software Engineer" },
      { label: "Session ID", value: sessionData.sessionId || "sess_unknown" },
      { label: "Date", value: new Date().toLocaleDateString() }
    ]
  );

  let y = startY;

  // Calculate Aggregates
  const evaluatedKeys = Object.keys(sessionData.evaluations || {});
  let totalScore = 0;
  let verdict: "Strong" | "Average" | "Needs Work" = "Average";

  if (evaluatedKeys.length > 0) {
    const sum = evaluatedKeys.reduce((acc, key) => acc + (sessionData.evaluations[Number(key)]?.score || 0), 0);
    totalScore = Math.round(sum / evaluatedKeys.length);
  }

  if (totalScore >= 80) verdict = "Strong";
  else if (totalScore >= 60) verdict = "Average";
  else verdict = "Needs Work";

  // Section 1: Overall Performance
  y = addSectionHeader(doc, "1. Overall Performance Summary", y);
  
  const perfRows = [
    ["Average Score", `${totalScore} / 100`],
    ["Performance Verdict", verdict],
    ["Total Completed Questions", `${evaluatedKeys.length} of ${sessionData.questions?.length || 5}`]
  ];

  autoTable(doc, {
    startY: y,
    head: [["Performance Criteria", "Assessment Result"]],
    body: perfRows,
    theme: "striped",
    headStyles: { fillColor: [124, 58, 237], textColor: [255, 255, 255], fontStyle: "bold" },
    bodyStyles: { textColor: [17, 17, 17], fontSize: 9 },
    alternateRowStyles: { fillColor: [249, 249, 249] },
    margin: { left: 20, right: 20 },
    didDrawPage: (data) => {
      y = data.cursor ? data.cursor.y + 25 : y + 90;
    }
  });

  // Section 2: Question by Question breakdown
  if (sessionData.questions && sessionData.questions.length > 0) {
    if (y > 750) { doc.addPage(); y = 40; }
    y = addSectionHeader(doc, "2. Detailed Q&A Breakdown", y);

    sessionData.questions.forEach((q: any, idx: number) => {
      if (y > 680) { doc.addPage(); y = 40; }

      // Q header
      doc.setFont("helvetica", "bold");
      doc.setFontSize(9);
      doc.setTextColor(124, 58, 237); // purple
      doc.text(`QUESTION ${idx + 1}:`, 30, y);
      y += 12;

      doc.setFont("helvetica", "normal");
      doc.setTextColor(17, 17, 17);
      const qTextLines = doc.splitTextToSize(`"${q.question}"`, 520);
      doc.text(qTextLines, 35, y);
      y += qTextLines.length * 12 + 4;

      // Answer
      const answer = sessionData.answers[q.id] || "No response provided.";
      doc.setFont("helvetica", "bold");
      doc.setTextColor(71, 85, 105);
      doc.text("Your Response:", 30, y);
      y += 12;

      doc.setFont("helvetica", "normal");
      doc.setTextColor(17, 17, 17);
      const ansLines = doc.splitTextToSize(`"${answer}"`, 520);
      doc.text(ansLines, 35, y);
      y += ansLines.length * 12 + 4;

      // Score / Verdict subline
      const evalObj = sessionData.evaluations[q.id];
      if (evalObj) {
        doc.setFont("helvetica", "bold");
        doc.setTextColor(17, 17, 17);
        doc.text(`Score: ${evalObj.score || 0}%  |  Confidence: ${evalObj.confidence || evalObj.confidence_rating || 0}%  |  Verdict: ${evalObj.verdict || "N/A"}`, 30, y);
        y += 15;

        // Strengths
        if (evalObj.strengths && evalObj.strengths.length > 0) {
          doc.setFont("helvetica", "bold");
          doc.setTextColor(16, 185, 129); // green
          doc.text("Strengths:", 35, y);
          y += 12;
          doc.setFont("helvetica", "normal");
          doc.setTextColor(17, 17, 17);
          evalObj.strengths.forEach((str: string) => {
            const strLines = doc.splitTextToSize(`• ${str}`, 500);
            doc.text(strLines, 40, y);
            y += strLines.length * 12;
          });
          y += 2;
        }

        // Improvements
        if (evalObj.improvements && evalObj.improvements.length > 0) {
          doc.setFont("helvetica", "bold");
          doc.setTextColor(225, 29, 72); // red
          doc.text("Improvements:", 35, y);
          y += 12;
          doc.setFont("helvetica", "normal");
          doc.setTextColor(17, 17, 17);
          evalObj.improvements.forEach((imp: string) => {
            const impLines = doc.splitTextToSize(`• ${imp}`, 500);
            doc.text(impLines, 40, y);
            y += impLines.length * 12;
          });
          y += 2;
        }

        // STAR rephrase
        const starRephrase = evalObj.starRephrase || evalObj.suggested_formulation;
        if (starRephrase) {
          if (y > 700) { doc.addPage(); y = 40; }
          doc.setFont("helvetica", "bold");
          doc.setTextColor(124, 58, 237);
          doc.text("STAR Formulation Re-phrase:", 35, y);
          y += 12;
          doc.setFont("helvetica", "italic");
          doc.setTextColor(17, 17, 17);
          const starLines = doc.splitTextToSize(starRephrase, 500);
          doc.text(starLines, 40, y);
          y += starLines.length * 12 + 15;
        }
      } else {
        doc.setFont("helvetica", "bold");
        doc.setTextColor(148, 163, 184);
        doc.text("AI Response Evaluation: Not Graded", 30, y);
        y += 25;
      }
    });
  }

  // Section 3: AI Body Language Tips (Static)
  if (y > 660) { doc.addPage(); y = 40; }
  y = addSectionHeader(doc, "3. AI Confidence Body Language tips", y);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(17, 17, 17);

  const tips = [
    "Maintain steady eye contact with the camera lens, not your monitor or preview panel.",
    "Ensure your workspace is front-lit and your physical background is clear of clutter.",
    "Speak at a measured, deliberate pace, pausing intentionally before key STAR transitions.",
    "Keep your posture straight and open — confident posture naturally filters into high vocal quality."
  ];

  tips.forEach((tip: string) => {
    const tipLines = doc.splitTextToSize(`✔  ${tip}`, 520);
    doc.text(tipLines, 30, y);
    y += tipLines.length * 12;
  });

  drawFooter(doc, "Generated by Syntrix AI Mock Interview Panel Simulator");
  doc.save(`syntrix-interview-report-${getFormattedDate()}.pdf`);
};
